---
title: "Lab 3"
subtitle: "Ordered and multinomial logistic regression"
author: Erik Gahner Larsen
date: Advanced applied statistics, 2015
output:
  ioslides_presentation:
    mathjax: "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
---

```{r include=FALSE}
library(ggplot2)

```

## Today

- Mandatory assignment 2
- Ordered logistic regression
- Multinomial logistic regression

## Mandatory assignment 2

1) Construct a causal model using Davis' (1985) guidelines on causal order. In connection with this, consider whether or not to include voting in elections (turnout).

2) Examine your causal model empiricially using linear and logistic regression.

3) Illustrate your results graphically by making at least two graphs of predicted probabilities.


## Tasks for lab session 3

Two tasks

a) Ordered logistic regression (Satisfaction with EU democracy)
    
b) Multinomial logistic regression (Party choice)

## Now

- Go to BlackBoard
- Download files for `lab 3`
- Work with the tasks
- If you need help, ask.
- Work in groups or alone
  
## Questions?

- Mail me or feel free to stop by my office

----